language: python
python: 3.7
install:
    - pip install --upgrade pip
    - pip install 'setuptools>=18.5'
    - pip install 'cwltool==1.0.20181217162649'
    - pip install 'ruamel.yaml==0.15.77'
    - pip install 'mdutils==1.0.0'
    - pip install 'PyYAML==5.1.2'

stages:
  - 'Tests'
  - name: 'Generate Docs'
    if: branch = master AND type = push

jobs:
  include:
    - stage: 'Tests'
      script:
        - find . -name '*.cwl' | xargs -n 1 cwltool --validate
    - stage: 'Generate Docs'
      script:
        - git clone "https://${GITHUB_TOKEN}@github.com/genome/analysis-workflows.wiki.git"
        - cd analysis-workflows.wiki/
        - python scripts/create_cwl_documentation.py
        - git add .
        - git diff-index --quiet HEAD || git commit -m "Automated Documentation Update\n${TRAVIS_BUILD_WEB_URL}"
        - git push

notifications:
  email: false
