instrument_data:
    - class: File
      path: gerald_H3MYFBBXX_4_GCCAAT_1k.bam
    - class: File
      path: gerald_H3MYFBBXX_5_GCCAAT_1k.bam
reference_index:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/hisat2.1.0_index/GRCh38DH
reference_annotation:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/Homo_sapiens.GRCh38DH.90.gtf
kallisto_index:
  class: File
  path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.kallisto.idx
gene_transcript_lookup_table:
  class: File
  path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/ensembl90.transcriptToGene.tsv
read_group_id:
    - '2895626107'
    - '2895626112'
read_group_fields:
    - ['PU:H3MYFBBXX5.4.GCCAAT', 'SM:H_NJ-HCC1395-HCC1395_RNA', 'LB:Pooled_RNA_2891007020-cD1-lib1', 'PL:Illumina', 'CN:WUGSC']
    - ['PU:H3MYFBBXX5.5.GCCAAT', 'SM:H_NJ-HCC1395-HCC1395_RNA', 'LB:Pooled_RNA_2891007020-cD1-lib1', 'PL:Illumina', 'CN:WUGSC']
trimming_adapters:
    class: File
    path: illumina_multiplex.fa
trimming_adapter_trim_end: 'RIGHT'
trimming_adapter_min_overlap: 7
trimming_max_uncalled: 300
trimming_min_readlength: 25
sample_name: H_NJ-HCC1395-HCC1395_RNA
firststrand: TRUE
refFlat:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.90.refFlat.txt
ribosomal_intervals:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38_U2AF1_fix/rna_seq_annotation/Homo_sapiens.GRCh38.90.rRNA.interval_list
strand: "SECOND_READ_TRANSCRIPTION_STRAND"
