#!/usr/bin/env cwl-runner
cwl:tool: pipeline.cwl
reference:
  class: File
  path: keep:591f8a4326389d97bbbb01ddd1bcd606+8203/GRCh38_full_analysis_set_plus_decoy_hla.fa
mills:
  class: File
  path: keep:591f8a4326389d97bbbb01ddd1bcd606+8203/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
known_indels:
  class: File
  path: keep:591f8a4326389d97bbbb01ddd1bcd606+8203/Homo_sapiens_assembly38.known_indels.vcf.gz
dbsnp:
  class: File
  path: keep:591f8a4326389d97bbbb01ddd1bcd606+8203/Homo_sapiens_assembly38.dbsnp138.vcf.gz
cosmic_vcf:
  class: File
  path: keep:591f8a4326389d97bbbb01ddd1bcd606+8203/Cosmic_v79.dictsorted.vcf.gz
interval_list:
  class: File
  path: keep:d8abfaae11ae3416b6bb95f72671d133+205/xgen-exome-research-panel-targets.interval_list
strelka_exome_mode: true
normal_bams:
  - { class: File, path: 'keep:941c6c78bb08a2c41685a5ad90b7371e+2270/gerald_H7HY2CCXX_3_ATCACGGT.bam' }
  - { class: File, path: 'keep:dcbb053a3c91d430478be8c6bfe673a8+2227/gerald_H7HY2CCXX_4_ATCACGGT.bam' }
normal_readgroups: ['@RG\tID:2895499223\tPL:ILLUMINA\tPU:H7HY2CCXX-ATCACGGT.3\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tSM:H_NJ-HCC1395-HCC1395', '@RG\tID:2895499237\tPL:ILLUMINA\tPU:H7HY2CCXX-ATCACGGT.4\tLB:H_NJ-HCC1395-HCC1395-lg24-lib1\tSM:H_NJ-HCC1395-HCC1395']
tumor_bams:
  - { class: File, path: 'keep:9058985e1fc8c14e505b451a6750b514+2228/gerald_H7HY2CCXX_3_TGACCACG.bam' }
  - { class: File, path: 'keep:74836c0e5588d30ae8e0ec6ac6af0f2d+2144/gerald_H7HY2CCXX_4_TGACCACG.bam' }
tumor_readgroups: ['@RG\tID:2895499331\tPL:ILLUMINA\tPU:H7HY2CCXX-TGACCACG.3\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tSM:H_NJ-HCC1395-HCC1395_BL', '@RG\tID:2895499399\tPL:ILLUMINA\tPU:H7HY2CCXX-TGACCACG.4\tLB:H_NJ-HCC1395-HCC1395_BL-lg21-lib1\tSM:H_NJ-HCC1395-HCC1395_BL']

