instrument_data_bams:
    - class: File
      path: test.bam
    - class: File
      path: test2.bam
outSAMattrRGline: 
    - ['ID:2895626107', 'PU:H3MYFBBXX5.4.GCCAAT', 'SM:H_NJ-HCC1395-HCC1395_RNA', 'LB:Pooled_RNA_2891007020-cD1-lib1', 'PL:Illumina', 'CN:WUGSC']
    - ['ID:2895626112', 'PU:H3MYFBBXX5.5.GCCAAT', 'SM:H_NJ-HCC1395-HCC1395_RNA', 'LB:Pooled_RNA_2891007020-cD1-lib1', 'PL:Illumina', 'CN:WUGSC']
trimming_adapters:
    class: File
    path: /gscmnt/gc2560/core/illumina_adapters/illumina_multiplex.fa
trimming_adapter_trim_end: 'RIGHT'
trimming_adapter_min_overlap: 7
trimming_max_uncalled: 300
trimming_min_readlength: 25
sample_name: H_NJ-HCC1395-HCC1395_RNA
kallisto_index:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/Homo_sapiens.GRCh38.cdna.all.fa.kallisto.idx
gene_transcript_lookup_table:
    class: File
    path: /gscmnt/gc2560/core/GRC-human-build38_human_90_38/rna_seq_annotation/ensembl90.transcriptToGene.tsv
outFileNamePrefix: H_NJ-HCC1395-HCC1395_RNA
outSAMunmapped: 'Within'
alignIntronMin: '20'
alignIntronMax: '1000000'
alignMatesGapMax: '1000000'
outSAMstrandField: intronMotif
twopassMode: 'basic'
runMode: "alignReads"
outSAMattributes: ['NH', 'HI', 'AS', 'NM', 'MD']
outFilterMultimapNmax: '20'
strand: first
sjdbOverhang: '100'
sjdbGTFfile:
    class: File
    path: /gscmnt/gc2733/walter/sridnona/refs/human/b38/GRCh38/Annotation/Homo_sapiens.GRCh38.95.gtf
genomeDir:
    class: Directory 
    path: /gscmnt/gc2733/walter/sridnona/refs/star_index_b38_95/
ribosomal_intervals: 
    class: File
    path: /gscmnt/gc2733/walter/sridnona/softwares/rnaseq_mgbio/Homo_sapiens.GRCh38.90.rRNA.interval_list
refFlat: 
    class: File
    path: /gscmnt/gc2733/walter/sridnona/softwares/rnaseq_mgbio/Homo_sapiens.GRCh38.90.refFlat.txt
