reference: ../GRCh38_full_analysis_set_plus_decoy_hla.fa
bams:
    - {class: File, path: ../input_A.bam}
    - {class: File, path: ../input_Z.bam}
readgroups: ['@RG\tID:A\tPL:Illumina\tSM:test-sample-1', '@RG\tID:Z\tPL:Illumina\tSM:test-sample-1']
dbsnp:
    class: File
    path: ../Homo_sapiens_assembly38.dbsnp138.vcf.gz
known_indels:
    class: File
    path: ../Homo_sapiens_assembly38.known_indels.vcf.gz
mills:
    class: File
    path: ../Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
